{-
   CVPartner

   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI Version: 3.0.1
   CVPartner API version: 0.0.1
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : CVPartner.API
-}

module CVPartner.API
  ( module CVPartner.API.ApiDefault
  ) where

import CVPartner.API.ApiDefault