{-
   CVPartner

   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI Version: 3.0.1
   CVPartner API version: 0.0.1
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : CVPartner.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module CVPartner.Logging
  ( module CVPartner.LoggingKatip
  ) where

import CVPartner.LoggingKatip

#else

module CVPartner.Logging
  ( module CVPartner.LoggingMonadLogger
  ) where

import CVPartner.LoggingMonadLogger

#endif
